export const FETCH_USERS_START = 'FETCH_USER_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USER_FAILURE';

export const DELETE_USER_START = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USERS_FAILURE';

