export const FETCH_USERS_START = 'FETCH_USER_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USER_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'GET_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USERS_FAILURE';

export const FILTER_USER_REQUEST = 'FILTER_USER_REQUEST';
export const FILTER_USER_SUCCESS = 'FILTER_USER_SUCCESS';
export const FILTER_USER_FAILURE = 'FILTER_USER_FAILURE';